name: Linting
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint

  stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run Stylelint
      run: npx stylelint **/*.css
